services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "9000:9000"
    volumes:
    - .:/var/www/html
    depends_on:
    - mysql
    environment:
      PHP_FPM_LISTEN: "9000"

  react:
    build:
      context: ./react
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
    working_dir: /app

    
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerix
      MYSQL_USER: commerix
      MYSQL_PASSWORD: commerix
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: