services:
  laravel:
    image: php:8.1-fpm
    container_name: laravel
    ports:
      - "9000:9000"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - PHP_FPM_LISTEN=9000

  react:
    image: node:18
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
